services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_manager
      MYSQL_USER: alfa
      MYSQL_PASSWORD: nasandratra
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  node-api:
    build: .
    container_name: node-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: sh -c "npm start"
    restart: always

volumes:
  mysql_data: